export const CREATE_PLAYER_REQUEST = "CREATE_PLAYER_REQUEST";
export const CREATE_PLAYER_SUCCESS = "CREATE_PLAYER_SUCCESS";
export const CREATE_PLAYER_FAIL = "CREATE_PLAYER_FAIL";

//Error constants
export const ERROR_MESSAGES_RESET = "ERROR_MESSAGES_RESET";
export const ERROR_MESSAGES_SUCCESS = "ERROR_MESSAGES_SUCCESS";
