export const CREATE_PLAYER_REQUEST = "CREATE_PLAYER_REQUEST";
export const CREATE_PLAYER_SUCCESS = "CREATE_PLAYER_SUCCESS";
export const CREATE_PLAYER_FAIL = "CREATE_PLAYER_FAIL";

export const GET_PLAYERS_LIST_REQUEST = "GET_PLAYERS_LIST_REQUEST";
export const GET_PLAYERS_LIST_SUCCESS = "GET_PLAYERS_LIST_SUCCESS";
export const GET_PLAYERS_LIST_FAIL = "GET_PLAYERS_LIST_FAIL";

export const GET_SHIP_LIST_REQUEST = "GET_SHIP_LIST_REQUEST";
export const GET_SHIP_LIST_SUCCESS = "GET_SHIP_LIST_SUCCESS";
export const GET_SHIP_LIST_FAIL = "GET_SHIP_LIST_FAIL";

//Error constants
export const ERROR_MESSAGES_RESET = "ERROR_MESSAGES_RESET";
export const ERROR_MESSAGES_SUCCESS = "ERROR_MESSAGES_SUCCESS";
